name: MLOps Pipeline

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  mlops:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dvc[all] scikit-learn pandas  # add your needed packages

    - name: Pull DVC data
      run: dvc pull

    - name: Run training script
      run: python src/train.py

    - name: Add model to DVC
      run: |
        dvc add models/model.pkl
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Action"
        git add models/model.pkl.dvc
        git commit -m "Update model from GitHub Actions" || echo "No changes to commit"

    - name: Push model artifacts to remote
      run: dvc push

    - name: Push changes back to repo
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
