name: FraudRadar MLOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  train_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dvc[all] scikit-learn imbalanced-learn mlflow uvicorn joblib fastapi requests

    - name: Pull data and models with DVC
      run: |
        dvc pull

    - name: Train model
      run: |
        python run_train.py

    - name: Push updated models with DVC
      run: |
        dvc add models/
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add models/.gitignore models/
        git commit -m "Update models after training [skip ci]" || echo "No changes to commit"
        git push

    - name: Build and push Docker images
      uses: docker/build-push-action@v4
      with:
        push: false
        tags: fraudradar-backend:latest, fraudradar-frontend:latest

    - name: Run backend tests (optional)
      run: |
        # Add tests here if you have any

